# Coveo settings
coveo_org_id: org_name
coveo_source_id: xxxxxxxxxxxxxxxxxxxxxxxxxx-org_name
coveo_api_key: Bearer xxxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

# Git settings
git_user: coveo-labs
git_api_key: token xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx